package vn.nuce.core.web.common;

public class WebConstant {
    public static final String MESSAGE_RESPONSE = "messageResponse";
    public static final String LOGIN_NAME = "loginName";
    public static final String FROM_ITEM = "item";
    public static final String LIST_ITEMS = "items";
    public static final String ORDER = "order";
    public static final String ORDER_USER = "orderUser";
    public static final String LIST_ITEMS_PRODUCER = "itemsProducer";
    public static final String LIST_ITEMS_PRODUCT = "itemsProduct";
    public static final String ALERT = "alert";
    public static final String TYPE_SUCCESS = "success";
    public static final String TYPE_ERROR = "danger";
    public static final String ROLE_ADMIN = "ADMIN";
    public static final String ROLE_USER = "USER";
    public static final String URL_LIST = "url_list";
    public static final String URL_EDIT = "url_edit";
    public static final String URL_KEY = "url_key";
    public static final String LISTENGUIDELINE = "listenguideline";
    public static final String INSERT_UPDATE = "insert_update";
    public static final String REDIRECT_INSERT = "redirect_insert";
    public static final String REDIRECT_UPDATE = "redirect_update";
    public static final String REDIRECT_DELETE = "redirect_delete";
    public static final String REDIRECT_ERROR = "redirect_error";
    public static final String LOGIN = "login";
    public static final String LOGOUT = "logout";
    public static final String REGISTER = "register";
    public static final String USER_ID = "userId";
    public static final String USER_ACCOUNT = "account";
    public static final String USER_PERSONAL = "personal";
    public static final String USER_CHANGE_PASSWORD = "change-password";
    public static final String USER_TRANSACTION = "transaction";
    public static final String CATEGORYS = "categorys";
    public static final String PRODUCERS = "producers";
    public static final String PRODUCT_INSERT = "insert";
    public static final String PRODUCT_UPDATE = "update";
    public static final String PRODUCT_DELETE = "delete";
    public static final String SORT_ASC = "asc";
    public static final String SORT_DESC = "desc";
    public static final String SORT_DEFAULT = "default";
    public static final String CHOSE = "chose";
    public static final String USER_PAYIN = "pay-in";
    public static final String BALANCE = "balance";
    public static final String ORDER_SIZE = "size";
    public static final String EARNINGS_MONTHLY = "earningsMonthly";
    public static final String EARNINGS_LIST = "earningsList";
}
